In [31]:
import torch

matrix=torch.randint(1,8,(2,3))

matrix



tensor([[7, 1, 1],
        [6, 4, 7]])

In [ ]:
import matplotlib.pyplot as plt
plt.figure(figsize=(10,10))

plt.imshow(matrix.numpy())
plt.axis('off')
plt.title('Random Matrix')
plt.colorbar()
plt.show()

In [12]:
scalar_toplam=matrix+10

scalar_toplam

tensor([[22, 24, 20],
        [22, 28, 20]])

In [18]:
scalar_cikarma=matrix-10

print('Cikarma:',scalar_cikarma)

scalar_carpma=matrix*10

print('Carpma:',scalar_carpma)

scalar_bolme=matrix/10

print('Bolme:',scalar_bolme)

scalar_ustu=matrix**10

print('Ustu:',scalar_ustu)


Cikarma: tensor([[2, 4, 0],
        [2, 8, 0]])
Carpma: tensor([[120, 140, 100],
        [120, 180, 100]])
Bolme: tensor([[1.2000, 1.4000, 1.0000],
        [1.2000, 1.8000, 1.0000]])
Ustu: tensor([[  61917364224,  289254654976,   10000000000],
        [  61917364224, 3570467226624,   10000000000]])


In [32]:
matrix2= torch.randint(1,6,(2,3))

matrix, matrix2

(tensor([[7, 1, 1],
         [6, 4, 7]]),
 tensor([[3, 5, 1],
         [3, 4, 5]]))

In [20]:
tensor_toplam=matrix+matrix2

tensor_toplam

tensor([[25, 43, 29],
        [31, 32, 36]])

In [21]:
tensor_toplam2=torch.add(matrix,matrix2)

tensor_toplam2

tensor([[25, 43, 29],
        [31, 32, 36]])

In [33]:
matrix, matrix2

(tensor([[7, 1, 1],
         [6, 4, 7]]),
 tensor([[3, 5, 1],
         [3, 4, 5]]))

In [26]:
tensor_carpma=torch.mul(matrix,matrix2)

print('Carpma:',tensor_carpma)

tensor_bolme=torch.div(matrix,matrix2)

print('Bolme:',tensor_bolme)



Carpma: tensor([[10,  5,  4],
        [ 5, 10,  5]])
Bolme: tensor([[0.4000, 0.2000, 0.2500],
        [0.2000, 0.4000, 0.2000]])


In [ ]:
cebirseel_carpma=torch.matmul(matrix,matrix2.T)

print('Cebirsel Carpma:',cebirseel_carpma)


Cebirsel Carpma: tensor([[27, 30],
        [45, 69]])
