In [12]:
import torch

In [13]:
vector = torch.tensor([3,4,5,6,7])
matrix = torch.tensor([[1,2,3], [4,5,6], [7,8,9]])
tensor = torch.tensor([[[1,2,3], [4,5,6], [7,8,9]], [[1,2,3], [4,5,6], [7,8,9]], [[1,2,3], [4,5,6], [7,8,9]]])
matrix= matrix.unsqueeze(0)

print(matrix.shape)
print(tensor.shape)

torch.Size([1, 3, 3])
torch.Size([3, 3, 3])


##### Tensor Olusturma

#ones
#zeros
#arange
#linspace
#eye

#rand
#randn
#randint  

In [17]:
vector = torch.ones(5)

print(vector)


tensor([1., 1., 1., 1., 1.])


In [ ]:
matrix = torch.ones(3,3)
print("Matrix:", matrix)

tensor = torch.ones(2,2,2)
print("Tensor:", tensor)

Matrix: tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
Tensor: tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])


In [24]:
td_tensor = torch.arange(1,9,1).reshape(2,2,2)
print("TD Tensor:", td_tensor)
td_tensor.shape, td_tensor.ndim

TD Tensor: tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])


(torch.Size([2, 2, 2]), 3)

In [26]:
matrix=torch.eye(4,4)
matrix

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [ ]:
vector=torch.linspace(0,10,steps=10).reshape(2,5)
vector

tensor([[ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444],
        [ 5.5556,  6.6667,  7.7778,  8.8889, 10.0000]])

In [ ]:
matrix=torch.randn(10,2)
matrix

tensor([[ 1.0802,  0.0975],
        [-0.2243,  0.7745],
        [-1.3057,  0.4149],
        [-0.2332,  0.0100],
        [-0.2680,  1.0843],
        [-0.0399, -1.4094],
        [-0.9123, -0.6834],
        [ 1.5793, -0.9035],
        [ 0.6474, -0.0529],
        [ 0.5242, -2.4531]])

In [45]:
matrix=torch.randint(30,50,(2,3,3))
matrix

tensor([[[30, 48, 34],
         [40, 36, 41],
         [30, 41, 39]],

        [[31, 49, 37],
         [36, 35, 32],
         [36, 41, 36]]])